; Configuration file for Duet 3 (firmware version 3.3)
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Mon Jul 18 2022 22:55:43 GMT+0200 (Central European Summer Time)

; General preferences
M575 P1 S1 B57600                            ; enable support for PanelDue
G90                                          ; send absolute coordinates...
M83                                          ; ...but relative extruder moves
M550 P"vd36hc"                               ; set printer name
M669 K1                                      ; select CoreXY mode

; Network
M552 S1 ; P192.168.101.183 S1                             ; enable network and acquire dynamic address via DHCP
M586 P0 S1                                   ; enable HTTP
M586 P1 S0                                   ; disable FTP
M586 P2 S0                                   ; disable Telnet

; Drives
M569 P0.0 S1                                 ; physical drive 0.0 goes forwards
M569 P0.1 S1                                 ; physical drive 0.1 goes forwards
M569 P0.2 S0                                 ; Extruder physical drive 0.2 goes forwards
M569 P0.3 S0                                 ; Z1 physical drive 0.3 goes forwards
M569 P0.4 S1                                 ; Z2 physical drive 0.3 goes forwards
M569 P0.5 S0                                 ; Z3 physical drive 0.3 goes forwards

M584 X0.0 Y0.1 E0.2 Z0.3:0.4:0.5                   ; set drive mapping
M350 Z16 E16 I0                              ; configure microstepping without interpolation
M350 X16 Y16 I1                              ; configure microstepping with interpolation
M92 X80.00 Y80.00 Z320.00 E932.00            ; set steps per mm
M566 X600.00 Y600.00 Z600.00 E600.00         ; set maximum instantaneous speed changes (mm/min)
M203 X30000.00 Y30000.00 Z1500.00 E9000.00   ; set maximum speeds (mm/min)
M201 X5000.00 Y5000.00 Z600.00 E5000.00      ; set accelerations (mm/s^2)
M906 X800 Y800 Z500 E900 I30                 ; set motor currents (mA) and motor idle factor in per cent
M84 S30                                      ; Set idle timeout

; Axis Limits
M208 X-18 Y-25 Z0 S1                               ; set axis minima
M208 X325 Y319 Z290 S0                         ; set axis maxima

; Endstops
M574 X1 S3                                   ; configure sensorless endstop for low end on X
M574 Y2 S3                                   ; configure sensorless endstop for high end on Y
M574 Z1 S2                                   ; configure Z-probe endstop for low end on Z

; Filament runout
M591 P1 C"io3.in" S1 D0 ; filament monitor connected to E0 endstop

; 3Z
M671 X-10:320:155 Y-10:-10:320 S10 				; leadscrews at front left, rear middle and front right

; Sensorless config
M915 P0:1 S4 F0 R0
M915 P0.3:0.4:0.5 S4 F0 R0

; Z-Probe
M558 P5 C"^io4.in" H15 F1500:600 T18000 A10 S0.03             ; set Z probe type to switch and the dive height + speeds

G31 P500 X0 Y-21 Z0                         ; set Z probe trigger value, offset and trigger height
M557 X15:295 Y10:290 S70:70                         ; define mesh grid

; Heaters
; bedtemp
M308 S0 P"temp0" Y"thermistor" T100000 B4138 A"Bed T°C" ; configure sensor 0 as thermistor on pin temp0
M950 H0 C"out3" T0                           ; create bed heater output on out0 and map it to sensor 0
M307 H0 B0 S1.00                             ; disable bang-bang mode for the bed heater and set PWM limit
M140 H0                                      ; map heated bed to heater 0
M143 H0 S130                                 ; set temperature limit for heater 0 to 130C

; hotend
M308 S1 P"temp1" Y"pt1000" A"Hotend T°C"                 ; configure sensor 1 as PT1000 on pin temp1
M950 H1 C"out1" T1                           ; create nozzle heater output on out1 and map it to sensor 1
M307 H1 B0 S1.00                             ; disable bang-bang mode for heater  and set PWM limit
M143 H1 S400                                 ; set temperature limit for heater 1 to 300C

; drybox
M308 S2 P"io6.out" Y"dht22" A"dbx Temp[C]"
; M308 S2 P"temp2" Y"thermistor" T100000 B4138 A"drybox T°C" ; configure sensor 3 as thermistor on pin duex.e2temp
M950 H2 C"out2" T2                          ; create chamber heater output on duex.e2heat and map it to sensor 3
M307 H2 B1 S0.1                                   ; bang-bang mode for the chamber heater and set PWM limit
M141 H2                                            ; map chamber to heater 3
M143 H2 S80                                       ; set temperature limit for heater 3 to 280C

; Chamber
M308 S3 P"temp3" Y"thermistor" T100000 B4138 A"Chamber T°C" ; configure sensor 3 as thermistor on pin duex.e2temp

; DHT Sensor on IO4 on Duet 3 6hc
M308 S4 P"S2.1" Y"dhthumidity" A"drybox Hum[%]" ; s11

; Fans
M950 F0 C"out4" Q500                         ; TOOL FAN create fan 0 on pin out4 and set its frequency
M106 P0 S0 H-1        C"Part Fan"                        ; set fan 0 value. Thermostatic control is turned off

M950 F1 C"out5" Q500                         ; COLDEND FAN create fan 1 on pin out5 and set its frequency
M106 P1 S1 H1 T45      C"H0 Fan"                       ; set fan 1 value. Thermostatic control is turned on

M950 F2 C"out8" Q500                         ; CHAMBER FAN create fan 2 on pin out6 and set its frequency
M106 P2 S0 H-1            C"Chamber Fan"                ; set fan 2 value. Thermostatic control is turned off

; MB Driver Fan
M950 F3 C"out9" Q500                         ; FILTER FAN create fan 2 on pin out6 and set its frequency
M106 P3 S0 H-1         C"MB Fan"               ; set fan 2 value. Thermostatic control is turned off

; Drybox Fan
M950 F4 C"out7" Q500                        ; Drybox FAN create fan 2 on pin out6 and set its frequency
M106 P4 S0 H-1        C"drybox fan"                ; set fan 2 value. Thermostatic control is turned off

; Tools
M563 P0 D0 H1 F0                             ; define tool 0
G10 P0 X0 Y0 Z0                              ; set tool 0 axis offsets
G10 P0 R0 S0                                 ; set initial tool 0 active and standby temperatures to 0C
T0 ; Select Tool 0

; Accelerometer
; M955 P0 C"spi.cs3+spi.cs2" I24 ; all wires connected to temp DB connector

; Inputshaping
; M593 P"zvddd" F40.0 ; use ZVD input shaping to cancel ringing at 40.5Hz

; PID Tuning
; M307 H1 R3.327 K0.444:0.000 D5.92 E1.35 S1.00 B0 V23.3 ; 70W dragon sf
M307 H1 R3.233 K0.425:0.117 D6.70 E1.35 S1.00 B0 V23.3 ; Mellow DG

M307 H0 R1.177 K0.810:0.000 D4.88 E1.35 S1.00 B0
M307 H2 R0.105 K0.033:0.000 D68.60 E1.35 S1.00 B0 ; drybox PTC heater BANG BANG

; drybox parameters
;Global varibles Drybox
global preSpoolWeight = 0
global emptySpoolWeight = 0
global totalWeight= 0
global filamentWeight =0
global dryBoxTC = 0
global dryBoxRH = 0
global calWeight =0 
global instructions = "No Message"

; call macros
M98 P"/macros/z_home_high" ;P define the parameter and is not part of the name
M98 P"/macros/z_offset"  ;P define the parameter and is not part of the name
M98 P"/macros/input_shaping_hz"  ;
M98 P"/macros/accel_set"  ;
M98 P"/macros/dbx_pwm" ;


