; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Mon Jul 18 2022 22:55:43 GMT+0200 (Central European Summer Time)
M280 P0 S90 ; retract BLTouch

